version: "3.8"
services:
    db:
        container_name: ${BOT_NAME}_db
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MYSQL_DATABASE: ${BOT_NAME}
            MYSQL_USER: ${BOT_NAME}_user
            MYSQL_PASSWORD: ${DB_PASS}
        volumes:
          - ./db/db_saves:/docker-entrypoint-initdb.d/:ro
        ports:
            - 3300:3306

    bot:
        container_name: ${BOT_NAME}_bot
        build: ./bot
        restart: always
        environment:
            DB_HOST: ${BOT_NAME}_db
            DB_NAME: ${BOT_NAME}
            DB_USER: ${BOT_NAME}_user
            DB_PASS: ${DB_PASS}
            DB_ROOT_PASS: ${DB_ROOT_PASS}
            TOKEN: ${TOKEN}
            GUILD_ID: ${GUILD_ID}
            BOT_ID: ${BOT_ID}
        depends_on:
            - db
        volumes:
            - ./db:/app/bot/db
